### PR TITLE
Initial commit for ansible-test support

### PR DESCRIPTION
**Pull request by wmudge**
Signed-off-by: Webster Mudge <wmudge@cloudera.com>

### CODE REVIEW

**Comment by Chaffelson** [comment]
@wmudge should this still be draft or did you want a review?

**Comment by wmudge** [comment]
Ready for review.

You can run this by executing the following:

```bash
# Sanity tests
ansible-test sanity --docker [--python 3.9]

# Unit tests (currently just the filter)
ansible-test units --docker [--python 3.9]

# And finally, the integration tests, which will spin up a Light and Medium (HA) duty environment using public/private networking
ansible-test integration --docker
```

Make sure you construct your own `integration_config.yml` file from the template. This will contain secrets, so should not be included in any repo.

**Review by jimright — COMMENTED** [review]
In general this looks good. 

Some comments/questions just to clarify before approval:
* Is it possible to run a test of idempotency with this or is that outside the scope of ansible-test?
* Some documentation for how to run these tests would be useful - e.g. in a TESTING.md or similar.
* Currently it is not possible to run these within cldr-runner the Container, only a venv. Is this expected or should there be another PR on cldr-runner to enable docker-in-docker support? 
* See comment about example password in `integration_config.yml_template` file.

**_Steps used to test:_**
* Checked-out feature branch of cloudera.exe for this PR. 
* Created a virtual env with all requirments as per https://github.com/cloudera-labs/cldr-runner#local-development
* From the exe directory:
  * Ran sanity check test suite with `ansible-test sanity --docker --python 3.9` - worked successfully
  * Ran unit test for combine_onto filter with `ansible-test units --docker --python 3.9` - worked successfully
  * Created a integration_config.yml file in tests/integration and ran integration tests with `ansible-test integration --docker`
    * Light Duty worked successfully. 
    * Then encountered a timeout due to CDP API during Medium Duty test. 
    * Re-ran from this point with `--start-at medium_duty_l1`.

**Review by jimright — APPROVED** [review]
Hey @wmudge -

Thanks for making the updated based on my initial review comments. I've re-tested this following your changes and all looks good.  The idempotency test catches the current issue where the CDP CLI ignores `default_sg` which is great. 

Approved.

**Pull request merged**
